require('dotenv').config();
const express = require('express');
const path = require('path');
const fs = require('fs');
const { initDb } = require('./db/database');
const uploadRoutes = require('./routes/upload.routes');
const dashboardRoutes = require('./routes/dashboard.routes');
const campaignRoutes = require('./routes/campaign.routes');
['uploads','screenshots','browser-profile'].forEach(d => fs.mkdirSync(path.join(__dirname, '..', d), { recursive: true }));
initDb();
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.set('view engine','ejs');
app.set('views', path.join(__dirname,'views'));
app.use('/public', express.static(path.join(__dirname, '..', 'public')));
app.use('/screenshots', express.static(process.env.SCREENSHOT_DIR || './screenshots'));
app.use('/', dashboardRoutes);
app.use('/upload', uploadRoutes);
app.use('/campaign', campaignRoutes);
const port = process.env.PORT || 3000;
app.listen(port, ()=>console.log(`Dashboard: http://localhost:${port}`));
